# Generated by Django 4.2.4 on 2023-10-04 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField()),
                ('professor', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('data_avaliacao', models.DateField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.curso')),
            ],
            options={
                'ordering': ['nota'],
            },
        ),
    ]
