# Generated by Django 4.2.4 on 2023-10-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_estudante_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pics/'),
        ),
    ]
