# Generated by Django 4.2.4 on 2023-10-04 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_estudante_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='estudante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='catalog.estudante'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EstudanteCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.curso')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.estudante')),
            ],
            options={
                'ordering': ['estudante'],
            },
        ),
    ]
