# Generated by Django 4.2.4 on 2023-10-04 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_nota_estudante_estudantecurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudantecurso',
            name='estudante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.estudante'),
        ),
    ]
