# Generated by Django 4.2.4 on 2023-10-04 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_estudantecurso_estudante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudantecurso',
            name='estudante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.estudante'),
        ),
    ]
