# Generated by Django 4.2.4 on 2023-10-04 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_estudantecurso_estudante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudantecurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.curso'),
        ),
        migrations.AlterField(
            model_name='estudantecurso',
            name='estudante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.estudante'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.curso'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='estudante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.estudante'),
        ),
    ]
