# Generated by Django 4.2.4 on 2023-10-04 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_estudantecurso_curso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='estudante',
        ),
        migrations.AddField(
            model_name='nota',
            name='cursoestudante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.estudantecurso'),
            preserve_default=False,
        ),
    ]
