# Generated by Django 4.2.4 on 2023-10-04 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_nota_curso_remove_nota_estudante_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota',
            old_name='cursoestudante',
            new_name='estudantecurso',
        ),
    ]
